mc = [
    'runNum', 'MC_condition', 'lumiSec', 'evtNum', 'mH', 'mX', 'ctau', 'npv', 'npu', 'weight', 'pileupWeight',
    'Flag_HBHENoiseFilter', 'Flag_BadPFMuonFilter', 'Flag_HBHEIsoNoiseFilter', 'Flag_CSCTightHaloFilter',
    'Flag_globalSuperTightHalo2016Filter', 'Flag_goodVertices', 'Flag_ecalBadCalibFilter',
    'Flag_BadChargedCandidateFilter', 'Flag_eeBadScFilter', 'Flag_all', 'Flag2_HBHENoiseFilter',
    'Flag2_HBHEIsoNoiseFilter', 'Flag2_BadPFMuonFilter', 'Flag2_globalSuperTightHalo2016Filter',
    'Flag2_globalTightHalo2016Filter', 'Flag2_BadChargedCandidateFilter', 'Flag2_EcalDeadCellTriggerPrimitiveFilter',
    'Flag2_ecalBadCalibFilter', 'Flag2_eeBadScFilter', 'Flag2_all', 'rho', 'met', 'metPhi', 'gHiggsPt', 'gHiggsE',
    'gHiggsEta', 'gHiggsPhi', 'nCscRings', 'nDtRings', 'nCscRechitClusters', 'cscRechitCluster_match_gLLP',
    'cscRechitCluster_match_gLLP_minDeltaR', 'cscRechitCluster_match_gLLP_index', 'cscRechitCluster_match_gLLP_eta',
    'cscRechitCluster_match_gLLP_phi', 'cscRechitCluster_match_gLLP_decay_r', 'cscRechitCluster_match_gLLP_decay_z',
    'cscRechitCluster_match_gLLP_csc', 'cscRechitCluster_match_gLLP_dt', 'cscRechitCluster_match_gLLP_e',
    'cscRechitClusterX', 'cscRechitClusterY', 'cscRechitClusterZ', 'cscRechitClusterTimeWeighted',
    'cscRechitClusterTimeSpreadWeightedAll', 'cscRechitClusterPhi', 'cscRechitClusterEta', 'cscRechitClusterJetVetoPt',
    'cscRechitClusterJetVetoLooseId', 'cscRechitClusterJetVetoTightId', 'cscRechitClusterJetVetoE',
    'cscRechitClusterMuonVetoPt', 'cscRechitClusterMuonVetoE', 'cscRechitClusterMuonVetoLooseId',
    'cscRechitClusterMuonVetoGlobal', 'cscRechitCluster_match_dtSeg_0p4', 'cscRechitCluster_match_MB1Seg_0p4',
    'cscRechitCluster_match_RE12_0p4', 'cscRechitCluster_match_RB1_0p4', 'cscRechitClusterSize',
    'cscRechitClusterNStation10', 'cscRechitClusterAvgStation10', 'cscRechitClusterMaxStation',
    'cscRechitClusterMaxStationRatio', 'cscRechitClusterNChamber', 'cscRechitClusterMaxChamber',
    'cscRechitClusterMaxChamberRatio', 'cscRechitClusterNRechitChamberPlus11', 'cscRechitClusterNRechitChamberPlus12',
    'cscRechitClusterNRechitChamberPlus13', 'cscRechitClusterNRechitChamberPlus21',
    'cscRechitClusterNRechitChamberPlus22', 'cscRechitClusterNRechitChamberPlus31',
    'cscRechitClusterNRechitChamberPlus32', 'cscRechitClusterNRechitChamberPlus41',
    'cscRechitClusterNRechitChamberPlus42', 'cscRechitClusterNRechitChamberMinus11',
    'cscRechitClusterNRechitChamberMinus12', 'cscRechitClusterNRechitChamberMinus13',
    'cscRechitClusterNRechitChamberMinus21', 'cscRechitClusterNRechitChamberMinus22',
    'cscRechitClusterNRechitChamberMinus31', 'cscRechitClusterNRechitChamberMinus32',
    'cscRechitClusterNRechitChamberMinus41', 'cscRechitClusterNRechitChamberMinus42', 'cscRechitClusterMet_dPhi',
    'nDtRechitClusters', 'dtRechitClusterNSegStation1', 'dtRechitClusterNSegStation2', 'dtRechitClusterNSegStation3',
    'dtRechitClusterNSegStation4', 'dtRechitClusterNOppositeSegStation1', 'dtRechitClusterNOppositeSegStation2',
    'dtRechitClusterNOppositeSegStation3', 'dtRechitClusterNOppositeSegStation4', 'dtRechitCluster_match_gLLP',
    'dtRechitCluster_match_gLLP_minDeltaR', 'dtRechitCluster_match_gLLP_index', 'dtRechitCluster_match_gLLP_eta',
    'dtRechitCluster_match_gLLP_phi', 'dtRechitCluster_match_gLLP_decay_r', 'dtRechitCluster_match_gLLP_decay_z',
    'dtRechitCluster_match_gLLP_csc', 'dtRechitCluster_match_gLLP_dt', 'dtRechitCluster_match_gLLP_e',
    'dtRechitClusterX', 'dtRechitClusterY', 'dtRechitClusterZ', 'dtRechitClusterWheel', 'dtRechitClusterPhi',
    'dtRechitClusterEta', 'dtRechitClusterJetVetoPt', 'dtRechitClusterJetVetoLooseId', 'dtRechitClusterJetVetoTightId',
    'dtRechitClusterJetVetoE', 'dtRechitClusterMuonVetoPt', 'dtRechitClusterMuonVetoE',
    'dtRechitClusterMuonVetoTightId', 'dtRechitClusterMuonVetoLooseId', 'dtRechitClusterMuonVetoGlobal',
    'dtRechitClusterOverlap', 'dtRechitClusterSize', 'dtRechitClusterNoiseHit', 'dtRechitClusterNoiseHitStation1',
    'dtRechitClusterNoiseHitStation2', 'dtRechitClusterNoiseHitStation3', 'dtRechitClusterNoiseHitStation4',
    'dtRechitClusterNStation10', 'dtRechitClusterAvgStation10', 'dtRechitClusterMaxStation',
    'dtRechitClusterMaxStationRatio', 'dtRechitClusterNChamber', 'dtRechitClusterMaxChamber',
    'dtRechitClusterMaxChamberRatio', 'dtRechitClusterNHitStation1', 'dtRechitClusterNHitStation2',
    'dtRechitClusterNHitStation3', 'dtRechitClusterNHitStation4', 'dtRechitClusterMet_dPhi',
    'dtRechitCluster_match_RPChits_dPhi0p5', 'dtRechitCluster_match_RPCBx_dPhi0p5', 'dtRechitCluster_match_RB1_0p4',
    'dtRechitCluster_match_RB1_dPhi0p5', 'dtRechitCluster_match_MB1Seg_0p4', 'dtRechitCluster_match_MB1Seg_0p5',
    'dtRechitCluster_match_MB1hits_0p4', 'dtRechitCluster_match_MB1hits_0p5',
    'dtRechitCluster_match_MB1hits_cosmics_plus', 'dtRechitCluster_match_MB1hits_cosmics_minus', 'nGLLP', 'gLLP_eta',
    'gLLP_phi', 'gLLP_csc', 'gLLP_dt', 'gLLP_beta', 'gLLP_e', 'gLLP_pt', 'gLLP_ctau', 'gLLP_decay_vertex_r',
    'gLLP_decay_vertex_x', 'gLLP_decay_vertex_y', 'gLLP_decay_vertex_z', 'nLeptons', 'lepE', 'lepPt', 'lepEta',
    'lepPhi', 'lepPdgId', 'lepDZ', 'lepTightId', 'lepPassLooseIso', 'lepPassTightIso', 'lepPassVTightIso',
    'lepPassVVTightIso', 'nJets', 'jetE', 'jetPt', 'jetEta', 'jetPhi', 'jetTightPassId', 'HLTDecision'
]

# run3 = [
#     'runNum', 'MC_condition', 'lumiSec', 'evtNum', 'mH', 'mX', 'ctau', 'npv', 'npu', 'weight', 'pileupWeight',
#     'Flag_HBHENoiseFilter', 'Flag_BadPFMuonFilter', 'Flag_HBHEIsoNoiseFilter', 'Flag_CSCTightHaloFilter',
#     'Flag_globalSuperTightHalo2016Filter', 'Flag_goodVertices', 'Flag_ecalBadCalibFilter',
#     'Flag_BadChargedCandidateFilter', 'Flag_eeBadScFilter', 'Flag_all', 'Flag2_HBHENoiseFilter',
#     'Flag2_HBHEIsoNoiseFilter', 'Flag2_BadPFMuonFilter', 'Flag2_globalSuperTightHalo2016Filter',
#     'Flag2_globalTightHalo2016Filter', 'Flag2_BadChargedCandidateFilter', 'Flag2_EcalDeadCellTriggerPrimitiveFilter',
#     'Flag2_ecalBadCalibFilter', 'Flag2_eeBadScFilter', 'Flag2_all', 'rho', 'met', 'metPhi', 'gHiggsPt', 'gHiggsE',
#     'gHiggsEta', 'gHiggsPhi', 'nCscRings', 'nDtRings', 'nCscRechitClusters', 'cscRechitCluster_match_gLLP',
#     'cscRechitCluster_match_gLLP_minDeltaR', 'cscRechitCluster_match_gLLP_index', 'cscRechitCluster_match_gLLP_eta',
#     'cscRechitCluster_match_gLLP_phi', 'cscRechitCluster_match_gLLP_decay_r', 'cscRechitCluster_match_gLLP_decay_z',
#     'cscRechitCluster_match_gLLP_csc', 'cscRechitCluster_match_gLLP_dt', 'cscRechitCluster_match_gLLP_e',
#     'cscRechitClusterX', 'cscRechitClusterY', 'cscRechitClusterZ', 'cscRechitClusterTimeWeighted',
#     'cscRechitClusterTimeSpreadWeightedAll', 'cscRechitClusterPhi', 'cscRechitClusterEta', 'cscRechitClusterJetVetoPt',
#     'cscRechitClusterJetVetoLooseId', 'cscRechitClusterJetVetoTightId', 'cscRechitClusterJetVetoE',
#     'cscRechitClusterMuonVetoPt', 'cscRechitClusterMuonVetoE', 'cscRechitClusterMuonVetoLooseId',
#     'cscRechitClusterMuonVetoGlobal', 'cscRechitCluster_match_dtSeg_0p4', 'cscRechitCluster_match_MB1Seg_0p4',
#     'cscRechitCluster_match_RE12_0p4', 'cscRechitCluster_match_RB1_0p4', 'cscRechitClusterSize',
#     'cscRechitClusterNStation10', 'cscRechitClusterAvgStation10', 'cscRechitClusterMaxStation',
#     'cscRechitClusterMaxStationRatio', 'cscRechitClusterNChamber', 'cscRechitClusterMaxChamber',
#     'cscRechitClusterMaxChamberRatio', 'cscRechitClusterNRechitChamberPlus11', 'cscRechitClusterNRechitChamberPlus12',
#     'cscRechitClusterNRechitChamberPlus13', 'cscRechitClusterNRechitChamberPlus21',
#     'cscRechitClusterNRechitChamberPlus22', 'cscRechitClusterNRechitChamberPlus31',
#     'cscRechitClusterNRechitChamberPlus32', 'cscRechitClusterNRechitChamberPlus41',
#     'cscRechitClusterNRechitChamberPlus42', 'cscRechitClusterNRechitChamberMinus11',
#     'cscRechitClusterNRechitChamberMinus12', 'cscRechitClusterNRechitChamberMinus13',
#     'cscRechitClusterNRechitChamberMinus21', 'cscRechitClusterNRechitChamberMinus22',
#     'cscRechitClusterNRechitChamberMinus31', 'cscRechitClusterNRechitChamberMinus32',
#     'cscRechitClusterNRechitChamberMinus41', 'cscRechitClusterNRechitChamberMinus42', 'cscRechitClusterMet_dPhi',
#     'nDtRechitClusters', 'dtRechitClusterNSegStation1', 'dtRechitClusterNSegStation2', 'dtRechitClusterNSegStation3',
#     'dtRechitClusterNSegStation4', 'dtRechitClusterNOppositeSegStation1', 'dtRechitClusterNOppositeSegStation2',
#     'dtRechitClusterNOppositeSegStation3', 'dtRechitClusterNOppositeSegStation4', 'dtRechitCluster_match_gLLP',
#     'dtRechitCluster_match_gLLP_minDeltaR', 'dtRechitCluster_match_gLLP_index', 'dtRechitCluster_match_gLLP_eta',
#     'dtRechitCluster_match_gLLP_phi', 'dtRechitCluster_match_gLLP_decay_r', 'dtRechitCluster_match_gLLP_decay_z',
#     'dtRechitCluster_match_gLLP_csc', 'dtRechitCluster_match_gLLP_dt', 'dtRechitCluster_match_gLLP_e',
#     'dtRechitClusterX', 'dtRechitClusterY', 'dtRechitClusterZ', 'dtRechitClusterWheel', 'dtRechitClusterPhi',
#     'dtRechitClusterEta', 'dtRechitClusterJetVetoPt', 'dtRechitClusterJetVetoLooseId', 'dtRechitClusterJetVetoTightId',
#     'dtRechitClusterJetVetoE', 'dtRechitClusterMuonVetoPt', 'dtRechitClusterMuonVetoE',
#     'dtRechitClusterMuonVetoTightId', 'dtRechitClusterMuonVetoLooseId', 'dtRechitClusterMuonVetoGlobal',
#     'dtRechitClusterOverlap', 'dtRechitClusterSize', 'dtRechitClusterNoiseHit', 'dtRechitClusterNoiseHitStation1',
#     'dtRechitClusterNoiseHitStation2', 'dtRechitClusterNoiseHitStation3', 'dtRechitClusterNoiseHitStation4',
#     'dtRechitClusterNStation10', 'dtRechitClusterAvgStation10', 'dtRechitClusterMaxStation',
#     'dtRechitClusterMaxStationRatio', 'dtRechitClusterNChamber', 'dtRechitClusterMaxChamber',
#     'dtRechitClusterMaxChamberRatio', 'dtRechitClusterNHitStation1', 'dtRechitClusterNHitStation2',
#     'dtRechitClusterNHitStation3', 'dtRechitClusterNHitStation4', 'dtRechitClusterMet_dPhi',
#     'dtRechitCluster_match_RPChits_dPhi0p5', 'dtRechitCluster_match_RPCBx_dPhi0p5', 'dtRechitCluster_match_RB1_0p4',
#     'dtRechitCluster_match_RB1_dPhi0p5', 'dtRechitCluster_match_MB1Seg_0p4', 'dtRechitCluster_match_MB1Seg_0p5',
#     'dtRechitCluster_match_MB1hits_0p4', 'dtRechitCluster_match_MB1hits_0p5',
#     'dtRechitCluster_match_MB1hits_cosmics_plus', 'dtRechitCluster_match_MB1hits_cosmics_minus', 'nGLLP', 'gLLP_eta',
#     'gLLP_phi', 'gLLP_csc', 'gLLP_dt', 'gLLP_beta', 'gLLP_e', 'gLLP_pt', 'gLLP_ctau', 'gLLP_decay_vertex_r',
#     'gLLP_decay_vertex_x', 'gLLP_decay_vertex_y', 'gLLP_decay_vertex_z', 'nLeptons', 'lepE', 'lepPt', 'lepEta',
#     'lepPhi', 'lepPdgId', 'lepDZ', 'lepTightId', 'lepPassLooseIso', 'lepPassTightIso', 'lepPassVTightIso',
#     'lepPassVVTightIso', 'nJets', 'jetE', 'jetPt', 'jetEta', 'jetPhi', 'jetTightPassId', 'HLTDecision'
# ]

# for k in run3:
#   if k not in mc:
#     print(k)

# print('')

# for k in mc:
#   if k not in run3:
#     print(k)
