#!/bin/bash

data_dir="/eos/user/f/fernanpe/displacedJetMuonAnalyzer_CA0p6_noMerging_240310_CSCOnly_DNNs/V1p19/hadd"

echo "building tarball"

tar -cvzf mds_run3_data.tar.xz \
    $data_dir/mc.root \
    $data_dir/data_2022.root \
    $data_dir/data_2022_goodLumi.root \
    $data_dir/mc_2023.root \
    $data_dir/data_2023.root \
    $data_dir/data_2023_goodLumi.root

echo "done"